### ISSUE TITLE
Numpy requirement for scikit-image should be >1.12 because of dask.array

### ISSUE THREAD

**Issue by carterbox** [conda-forge/scikit-image-feedstock#50]
Scikit-image is using `dask.array`. This requires `numpy>1.12` because otherwise NumPy has no module named `divmod`. You can see the import failure of `dask.array` with `numpy<=1.12` here: https://github.com/conda-forge/dask-core-feedstock/issues/45.

This dependency of `daks.array` on NumPy is noted in the Scikit-image recipe:

https://github.com/conda-forge/scikit-image-feedstock/blob/346cbd8a7129b817ddc96bf0ab827a383ac1f2fc/recipe/meta.yaml#L53-L56

However, NumPy is only pinned to a "compatible" version which could be <=1.12. Thus a stronger dependency requirement is needed.

**Comment by hmaarrfk** [comment]
i mean, conda-forge pins numpy to 1.14 during build if not specified. 

```
requirements:
    build:
        - vs2015_win-64 14.0.25420 h55c1224_11
    host:
        - certifi 2019.3.9 py36_0
        - cython 0.29.10 py36h6538335_0
        - intel-openmp 2019.4 245
        - libblas 3.8.0 8_mkl
        - libcblas 3.8.0 8_mkl
        - liblapack 3.8.0 8_mkl
        - mkl 2019.4 245
        - numpy 1.14.6 py36h873a0b8_1201
        - pip 19.1.1 py36_0
        - python 3.6.7 he025d50_1004
        - setuptools 41.0.1 py36_0
        - vc 14.1 h0510ff6_4
        - vs2015_runtime 14.15.26706 h3a45250_4
        - wheel 0.33.4 py36_0
        - wincertstore 0.2 py36_1002
    run:
        - cloudpickle >=0.2.1
        - cytoolz >=0.7.3
        - dask-core >=0.9.0
        - imageio >=2.1.0
        - matplotlib-base >=2.0.0
        - networkx >=1.8
        - numpy >=1.14.6,<2.0a0
        - pillow >=4.3.0
        - python >=3.6,<3.7.0a0
        - pywavelets >=0.4.0
        - scipy >=0.17
        - toolz >=0.7.4
        - vc >=14,<15.0a0
```

These are the generated dependencies that can be seen in `index.json`

```
{
  "arch": "x86_64",
  "build": "py36he350917_2",
  "build_number": 2,
  "depends": [
    "cloudpickle >=0.2.1",
    "cytoolz >=0.7.3",
    "dask-core >=0.9.0",
    "imageio >=2.1.0",
    "matplotlib-base >=2.0.0",
    "networkx >=1.8",
    "numpy >=1.14.6,<2.0a0",
    "pillow >=4.3.0",
    "python >=3.6,<3.7.0a0",
    "pywavelets >=0.4.0",
    "scipy >=0.17",
    "toolz >=0.7.4",
    "vc >=14,<15.0a0"
  ],
  "license": "BSD 3-Clause",
  "name": "scikit-image",
  "platform": "win",
  "subdir": "win-64",
  "timestamp": 1560560994917,
  "version": "0.15.0"
}
```
